#spring.application.name=litemall_back;
server:
  port: 9090
spring:
  application:
    name: litemall_back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:aws-wrapper:mysql://localhost:3306/litemall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: litemall
    password: litemall123456
